import * as THREE from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { DRACOLoader } from 'three/addons/loaders/DRACOLoader.js';
const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)], clamp=(n,a=0,b=1)=>Math.min(b,Math.max(a,n));
const reduceMotionMedia=matchMedia('(prefers-reduced-motion: reduce)');
let reduceMotion=reduceMotionMedia.matches;
reduceMotionMedia.addEventListener('change',event=>{reduceMotion=event.matches});
const projects=[
 {name:'Poster Buron',full:'Poster Buron Generator',description:'Turn your photo and social identity into a shareable Indonesian-style wanted poster, ready to post on Threads.',url:'https://posterburon.annetta.dev',status:'Live',stack:'Web app · Image tools',role:'Creator & developer',year:'2026',color:'#f06c4f',image:'./public/assets/projects/poster-buron-generator.png',imageAlt:'Paper-collage illustration of a photo becoming a vintage fugitive poster'},
 {name:'One Piece Bounty Poster',full:'One Piece Bounty Poster Generator',description:'Create a custom One Piece–style bounty poster directly in the browser.',url:'https://posteronepiece.annetta.dev',status:'In progress',stack:'Web app · Canvas',role:'Creator & developer',year:'2026',color:'#f5b842',image:'./public/assets/projects/one-piece-poster-generator.png',imageAlt:'Paper-collage illustration of a pirate bounty poster surrounded by nautical objects'},
 {name:'One Call Away',full:'One Call Away',description:'A gentle reminder app for keeping up with the people you care about.',url:'https://onecallaway.annetta.dev',status:'In progress',stack:'Product · Full stack',role:'Product & engineering',year:'2026',color:'#f397aa',image:'./public/assets/projects/one-call-away.png',imageAlt:'Paper-collage illustration of a phone connecting friends and family through reminders'},
 {name:'Cozy Pomodoro',full:'Cozy Pomodoro',description:'A calm focus timer with an animal companion that works alongside you.',url:'https://pomodoro.annetta.dev',status:'In progress',stack:'Web app · Animation',role:'Creator & developer',year:'2026',color:'#73bda8',image:'./public/assets/projects/cozy-pomodoro.png',imageAlt:'Paper-collage illustration of a tomato timer and a cozy animal companion'},
 {name:'Chord Analyzer',full:'Chord Analyzer',description:'Follow synchronized chord diagrams while an MP3 or YouTube video plays.',url:'https://chord.annetta.dev',status:'Concept',stack:'Audio · AI · Web',role:'Engineering',year:'2026',color:'#838bc9',image:'./public/assets/projects/chord-analyzer.png',imageAlt:'Paper-collage illustration of a guitar, audio waveform, and chord diagrams'}];
const skills=[['Frontend',8],['Backend',8],['Infrastructure / DevOps',7],['Design',7],['Product Management',7],['AI',8]];

const projectSlots=[
 {x:25,y:36,w:8,h:15,label:'COLA'},
 {x:52.5,y:17.2,w:8,h:15,label:'LEMON'},
 {x:66.2,y:36,w:8,h:15,label:'PEACH'},
 {x:52.5,y:53.5,w:8,h:14,label:'YUZU'},
 {x:73.2,y:53.5,w:8,h:14,label:'AQUA'}
];
projects.forEach((project,index)=>{
 const slot=projectSlots[index];
$('#product-grid').insertAdjacentHTML('beforeend',`<div class="product-item" role="listitem" style="--slot-x:${slot.x}%;--slot-y:${slot.y}%;--slot-w:${slot.w}%;--slot-h:${slot.h}%;--shine-delay:${index*.83}s"><button class="product" type="button" data-index="${index}" aria-label="Open ${project.full} from the ${slot.label} drink"><span class="product-gloss" aria-hidden="true"></span><span class="product-sparkles" aria-hidden="true"><i></i><i></i><i></i></span><span class="product-pick-cue" aria-hidden="true">Pick me</span><span class="visually-hidden">${project.full}</span></button></div>`);
 $('#project-list').insertAdjacentHTML('beforeend',`<div role="listitem"><button class="project-list-item" type="button" data-index="${index}" aria-label="Open ${project.full}"><span class="project-list-number">${String(index+1).padStart(2,'0')}</span><span class="project-list-name">${project.name}</span><span class="project-list-arrow" aria-hidden="true">+</span></button></div>`)
});
skills.forEach(([name,score],i)=>{
 const reverse=i%2===1;
 $('#skill-list').insertAdjacentHTML('beforeend',`<div class="skill-row${reverse?' lap-reverse':''}" tabindex="0" style="--lap-p:0;--lap-pct:0%;--swimmer-x:0px" aria-label="${name}. Full lap. Self-rating ${score} out of 10."><div class="skill-name"><span>${String(i+1).padStart(2,'0')}</span><strong>${name}</strong></div><div class="lane" aria-hidden="true"><i class="lane-wake"></i><img class="lane-swimmer" src="./public/assets/characters/swim/annetta-swim-cutout.png" alt="" width="1544" height="505" decoding="async"></div><output aria-label="Self-rating ${score} out of 10"><span>Self-rating</span><strong>${score}<small>/10</small></strong></output></div>`)
});

const projectModal=$('#project-modal'),projectSection=$('#projects'),machineWrap=$('.machine-wrap');
let lastProduct,modalGrowTimer,projectCueTimer,projectCueActive=false,projectCuePlayed=false,projectCueLockY=0,projectSceneReady=false;
function scrollInstantly(top){const root=document.documentElement,behavior=root.style.scrollBehavior;root.style.scrollBehavior='auto';scrollTo(0,top);root.style.scrollBehavior=behavior}
function lockProjectScroll(){projectCueLockY=scrollY;document.body.style.setProperty('--project-cue-lock-y',`-${projectCueLockY}px`);document.body.classList.add('project-cue-lock')}
function unlockProjectScroll(){if(!document.body.classList.contains('project-cue-lock'))return;document.body.classList.remove('project-cue-lock');document.body.style.removeProperty('--project-cue-lock-y');scrollInstantly(projectCueLockY)}
function finishProjectCue(){if(!projectCueActive)return;projectCueActive=false;clearTimeout(projectCueTimer);projectSection.classList.remove('project-cue-active');unlockProjectScroll()}
function populateProjectModal(index){const project=projects[index];$('#modal-title').textContent=project.full;$('#modal-description').textContent=project.description;$('#modal-stack').textContent=project.stack;$('#modal-role').textContent=project.role;$('#modal-year').textContent=project.year;$('#modal-status').textContent=project.status;$('#modal-status').className=`status-badge ${project.status==='In progress'?'wip':''}`;$('#project-preview').style.setProperty('--project-color',project.color);$('#project-preview').innerHTML=`<img class="project-header-image" src="${project.image}" alt="${project.imageAlt}" width="2048" height="768" decoding="async">`;$('#modal-link').href=project.url;$('#modal-link').style.display=project.url==='#'?'none':'inline-flex'}
function openProject(index,{origin=$(`.product[data-index="${index}"]`)}={}){
 if(projectModal.open)return;const duration=reduceMotion?0:300;lastProduct=origin;populateProjectModal(index);
 projectModal.classList.remove('modal-origin-grow');projectModal.classList.add('modal-preparing');projectModal.showModal();
 const modalRect=projectModal.getBoundingClientRect(),originRect=origin?.getBoundingClientRect();if(originRect){projectModal.style.setProperty('--modal-origin-x',`${originRect.left+originRect.width/2-modalRect.left}px`);projectModal.style.setProperty('--modal-origin-y',`${originRect.top+originRect.height/2-modalRect.top}px`)}
 requestAnimationFrame(()=>{projectModal.classList.remove('modal-preparing');if(duration)projectModal.classList.add('modal-origin-grow')});
 clearTimeout(modalGrowTimer);modalGrowTimer=setTimeout(()=>projectModal.classList.remove('modal-origin-grow'),duration+40);
}
function closeModal(){if(projectModal.open)projectModal.close()}
function selectProject(index,origin){projectCuePlayed=true;clearTimeout(projectCueTimer);openProject(index,{origin})}
$('#product-grid').addEventListener('click',event=>{const product=event.target.closest('.product');if(product)selectProject(+product.dataset.index,product)});
$('#project-list').addEventListener('click',event=>{const item=event.target.closest('.project-list-item');if(item)selectProject(+item.dataset.index,item)});
$('.modal-close').addEventListener('click',closeModal);
projectModal.addEventListener('click',event=>{if(event.target===projectModal)closeModal()});
projectModal.addEventListener('close',()=>{projectModal.classList.remove('modal-preparing','modal-origin-grow');finishProjectCue();lastProduct?.focus({preventScroll:true})});
function machineFullyVisible(){const rect=machineWrap.getBoundingClientRect();return rect.height>0&&rect.top>=8&&rect.bottom<=innerHeight-8}
function maybeStartProjectCue(){if(!projectSceneReady||projectCueActive||projectCuePlayed||projectModal.open||!machineFullyVisible())return;projectCuePlayed=true;projectCueActive=true;projectSection.classList.add('project-cue-active');lockProjectScroll();projectCueTimer=setTimeout(()=>openProject(0),reduceMotion?0:820)}
const waitForProjectImage=src=>new Promise(resolve=>{const image=new Image();image.onload=()=>image.decode?image.decode().catch(()=>{}).finally(resolve):resolve();image.onerror=resolve;image.src=src});
const projectPreloader=new IntersectionObserver(entries=>{if(!entries.some(entry=>entry.isIntersecting))return;projectPreloader.disconnect();Promise.all(['./public/assets/vending/machine.png','./public/assets/vending/background.png','./public/assets/characters/vending/annetta.png',projects[0].image].map(waitForProjectImage)).then(()=>{projectSceneReady=true;maybeStartProjectCue()})},{rootMargin:'100% 0px'});
projectPreloader.observe(projectSection);addEventListener('scroll',maybeStartProjectCue,{passive:true});addEventListener('resize',maybeStartProjectCue,{passive:true});
$('#year').textContent=new Date().getFullYear();

const walkFrames=Array.from({length:8},(_,i)=>`./public/assets/characters/bio-walk/${i+1}.png`);
const slipFrames=Array.from({length:12},(_,i)=>`./public/assets/characters/slip/${i+3}.png`);
const walker=$('#walk-sprite'),returnWalker=$('#return-walk-sprite');
const slipTiming={prepFrame:70,prepFrames:3,fallFrame:90,fallFrames:6,impact:170,stunned:320,recoveryFrame:180,recoveryFrames:5};
const returnCenterProgress=50/115;
const returnMotion={sequenceActive:false,slipFramesReady:false,played:false,pending:false,animationStart:0,progress:0,anchorY:0,pendingAnchorY:0};
let latestTouchY=0;
const preloadImages=sources=>Promise.all(sources.map(src=>new Promise(resolve=>{const image=new Image();image.onload=()=>{if(image.decode)image.decode().catch(()=>{}).finally(resolve);else resolve()};image.onerror=resolve;image.src=src})));
const preloadCharacterFrames=()=>{preloadImages(walkFrames).then(()=>{walker.classList.add('ready');returnWalker.classList.add('ready')});if(!reduceMotion)preloadImages(slipFrames).then(()=>{returnMotion.slipFramesReady=true;updateScroll()})};
if('requestIdleCallback'in window)requestIdleCallback(preloadCharacterFrames,{timeout:1200});else setTimeout(preloadCharacterFrames,500);

let lastAbout=0,lastReturn=0,movingTimer,slipAnimationFrame;

function showReturnFrame(src,state){if(returnWalker.getAttribute('src')!==src)returnWalker.src=src;returnWalker.dataset.motionState=state}
function preventForwardTouch(event){const touchY=event.touches[0]?.clientY??latestTouchY;if(touchY<latestTouchY)event.preventDefault();latestTouchY=touchY}
function finishReturnSlip(){returnMotion.sequenceActive=false;returnMotion.animationStart=0;removeEventListener('touchmove',preventForwardTouch);document.documentElement.style.setProperty('--return-p',returnMotion.progress);showReturnFrame(walkFrames[Math.floor(returnMotion.progress*48)%walkFrames.length],'walking');updateScroll()}
function holdReturnScroll(){if(returnMotion.sequenceActive&&scrollY>returnMotion.anchorY+.5)scrollInstantly(returnMotion.anchorY)}
function animateReturnSlip(now){
 const elapsed=now-returnMotion.animationStart,prepDuration=slipTiming.prepFrame*slipTiming.prepFrames,fallDuration=slipTiming.fallFrame*slipTiming.fallFrames,impactDuration=slipTiming.impact+slipTiming.stunned,recoveryDuration=slipTiming.recoveryFrame*slipTiming.recoveryFrames;
 if(elapsed<prepDuration){showReturnFrame(walkFrames[Math.floor(elapsed/slipTiming.prepFrame)%walkFrames.length],'fast-walking')}
 else if(elapsed<prepDuration+fallDuration){showReturnFrame(slipFrames[Math.floor((elapsed-prepDuration)/slipTiming.fallFrame)],'slipping')}
 else if(elapsed<prepDuration+fallDuration+impactDuration){showReturnFrame(slipFrames[6],'slipping')}
 else if(elapsed<prepDuration+fallDuration+impactDuration+recoveryDuration){showReturnFrame(slipFrames[7+Math.floor((elapsed-prepDuration-fallDuration-impactDuration)/slipTiming.recoveryFrame)],'recovering')}
 else{finishReturnSlip();return}
 document.documentElement.style.setProperty('--return-p',returnCenterProgress);
 slipAnimationFrame=requestAnimationFrame(animateReturnSlip)
}
function startReturnSlip(anchorY){
 if(reduceMotion||returnMotion.sequenceActive||returnMotion.played||!returnMotion.slipFramesReady)return;
 returnMotion.sequenceActive=true;returnMotion.played=true;returnMotion.pending=false;returnMotion.anchorY=anchorY;returnMotion.animationStart=performance.now();addEventListener('touchmove',preventForwardTouch,{passive:false});holdReturnScroll();
 cancelAnimationFrame(slipAnimationFrame);animateReturnSlip(returnMotion.animationStart)
}
const pageHero=$('#hero'),pageAbout=$('#about'),skillList=$('#skill-list'),returnWalk=$('.return-walk'),siteNav=$('#site-nav');
const sectionLinks=['about','projects','skills','contact'].map(id=>({section:$(`#${id}`),link:$(`.site-nav a[href="#${id}"]`)}));
const skillRows=$$('.skill-row',skillList).map(row=>({row,lane:row.querySelector('.lane'),swimmer:row.querySelector('.lane-swimmer'),reverse:row.classList.contains('lap-reverse'),travel:0}));
function measureSkillLanes(){skillRows.forEach(item=>{item.travel=Math.max(0,item.lane.clientWidth-(item.swimmer.offsetWidth||88))})}
measureSkillLanes();
function updateScroll(){
 const y=scrollY,vh=innerHeight,hp=clamp(y/Math.max(1,pageHero.offsetHeight-vh));document.documentElement.style.setProperty('--hero-p',hp);
 const ar=pageAbout.getBoundingClientRect(),ap=clamp((vh-ar.top)/(vh*.65)),walkP=clamp((vh-ar.top)/(vh+ar.height*.78)),walkerX=(-.12+walkP*1.24)*ar.width,inWalkway=walkP>0&&walkP<1;
 document.documentElement.style.setProperty('--about-p',ap);walker.style.setProperty('--walker-x',`${walkerX.toFixed(1)}px`);walker.classList.toggle('active',inWalkway);
 if(inWalkway&&Math.abs(walkP-lastAbout)>.00025){walker.src=walkFrames[Math.floor(walkP*72)%walkFrames.length];walker.classList.add('walking');clearTimeout(movingTimer);movingTimer=setTimeout(()=>{walker.classList.remove('walking');walker.src=walkFrames[0]},130)}
 lastAbout=walkP;
 const skillListRect=skillList.getBoundingClientRect(),lapSequence=reduceMotion?1:clamp((vh*.78-skillListRect.top)/(vh*.72+skillListRect.height*.3));
 skillRows.forEach(({row,reverse,travel},i)=>{const lapP=clamp(lapSequence*skills.length-i),swimmerX=(reverse?1-lapP:lapP)*travel;row.style.setProperty('--lap-pct',`${(lapP*100).toFixed(2)}%`);row.style.setProperty('--swimmer-x',`${swimmerX.toFixed(1)}px`);row.classList.toggle('lap-active',lapP>0&&lapP<.995);row.classList.toggle('lap-complete',lapP>=.995)});
 const rr=returnWalk.getBoundingClientRect(),rp=clamp((vh*.88-rr.top)/(vh+rr.height*.35)),corridorVisible=rr.top<vh&&rr.bottom>0;returnMotion.progress=rp;
 if(!returnMotion.sequenceActive)document.documentElement.style.setProperty('--return-p',rp);
 if(!returnMotion.sequenceActive&&rp<.12){returnMotion.played=false;returnMotion.pending=false}
 if(corridorVisible&&rp>lastReturn&&lastReturn<returnCenterProgress&&rp>=returnCenterProgress&&!returnMotion.played){returnMotion.pending=true;returnMotion.pendingAnchorY=y+rr.top-vh*.88+returnCenterProgress*(vh+rr.height*.35)}
 if(returnMotion.pending&&returnMotion.slipFramesReady)startReturnSlip(returnMotion.pendingAnchorY);
 if(!returnMotion.sequenceActive&&rp>0&&rp<1)showReturnFrame(walkFrames[Math.floor(rp*48)%walkFrames.length],'walking');
 lastReturn=rp;
 siteNav.classList.toggle('visible',hp>.82||y>pageHero.offsetHeight-vh*.1);let activeSection;sectionLinks.forEach(item=>{if(item.section.getBoundingClientRect().top<vh*.5)activeSection=item.section});sectionLinks.forEach(item=>item.link.classList.toggle('active',item.section===activeSection))
}
let scrollUpdateQueued=false;function scheduleScrollUpdate(){holdReturnScroll();if(scrollUpdateQueued)return;scrollUpdateQueued=true;requestAnimationFrame(()=>{scrollUpdateQueued=false;updateScroll()})}addEventListener('scroll',scheduleScrollUpdate,{passive:true});addEventListener('wheel',event=>{if(returnMotion.sequenceActive&&event.deltaY>0)event.preventDefault()},{passive:false});addEventListener('touchstart',event=>{latestTouchY=event.touches[0]?.clientY??latestTouchY},{passive:true});addEventListener('keydown',event=>{const editing=event.target instanceof Element&&event.target.closest('input,textarea,select,button');if(returnMotion.sequenceActive&&['ArrowDown','PageDown','End',' '].includes(event.key)&&!editing)event.preventDefault()});addEventListener('resize',()=>{measureSkillLanes();scheduleScrollUpdate()});updateScroll();
new IntersectionObserver(entries=>entries.forEach(entry=>entry.target.classList.toggle('scene-entered',entry.isIntersecting)),{threshold:.18}).observe($('#projects'));
$$('.paper-world,.tile-world').forEach(section=>section.addEventListener('pointerdown',event=>{if(event.target.closest('a,button,[tabindex]'))return;const ripple=document.createElement('i');ripple.className='surface-ripple';const rect=section.getBoundingClientRect();ripple.style.left=`${event.clientX-rect.left}px`;ripple.style.top=`${event.clientY-rect.top}px`;section.append(ripple);ripple.addEventListener('animationend',()=>ripple.remove())},{passive:true}));
$$('[data-skip-intro]').forEach(b=>b.addEventListener('click',e=>{$('#loader').classList.add('hidden');$('#site-nav').classList.add('visible');$('#about').scrollIntoView({behavior:reduceMotion?'auto':'smooth'});if(e.detail===0)setTimeout(()=>$('#about').focus(),350)}));

const socialLinks={instagram:'https://www.instagram.com/aintrsln/',threads:'https://www.threads.com/@aintrsln',github:'https://github.com/ant133',email:'mailto:annettaarslan@gmail.com'};
const wrap=$('#canvas-wrap'),letters=[],passiveFloats=[],socialMeshes=[],ripples=[],raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2(9,9),hit=new THREE.Vector3(),plane=new THREE.Plane(new THREE.Vector3(0,1,0),0);
let renderer,scene,camera,waterGeom,basePositions,caustics,dragged=null,hovered=null,hoveredSocial=null,socialPress=null,pointerId=null;
const config={size:30,segments:innerWidth<700?16:36,frameStride:innerWidth<700?3:2,wave:.10,damping:.965,angularDamping:.94,dragSpring:.15,dragLift:.82,colors:[0xff6e7e,0xffbd55,0x78d5bb,0x70b9ef,0xb59ae8,0xff8eb5,0x50c3d2]};
function roundedBox(w,h,d,r=.2){const s=new THREE.Shape(),x=-w/2,y=-h/2;s.moveTo(x+r,y);s.lineTo(x+w-r,y);s.quadraticCurveTo(x+w,y,x+w,y+r);s.lineTo(x+w,y+h-r);s.quadraticCurveTo(x+w,y+h,x+w-r,y+h);s.lineTo(x+r,y+h);s.quadraticCurveTo(x,y+h,x,y+h-r);s.lineTo(x,y+r);s.quadraticCurveTo(x,y,x+r,y);const g=new THREE.ExtrudeGeometry(s,{depth:d,bevelEnabled:true,bevelSegments:3,bevelSize:r*.4,bevelThickness:r*.4,curveSegments:6});g.center();return g}
function bar(g,m,w,h,x,y,a=0){const o=new THREE.Mesh(roundedBox(w,h,.58,Math.min(w,h)*.3),m);o.position.set(x,y,0);o.rotation.z=a;o.castShadow=true;g.add(o)}
function makeLetter(char,color){const g=new THREE.Group(),m=new THREE.MeshPhysicalMaterial({color,emissive:new THREE.Color(color).multiplyScalar(.12),emissiveIntensity:0,roughness:.2,clearcoat:1,clearcoatRoughness:.07,sheen:1,sheenColor:new THREE.Color(color).lerp(new THREE.Color(0xffffff),.5),sheenRoughness:.22});if(char==='A'){bar(g,m,.47,2.45,-.38,0,-.23);bar(g,m,.47,2.45,.38,0,.23);bar(g,m,.92,.36,0,-.04)}if(char==='N'){bar(g,m,.46,2.5,-.48,0);bar(g,m,.46,2.5,.48,0);bar(g,m,.48,2.63,0,0,.37)}if(char==='E'){bar(g,m,.46,2.5,-.43,0);bar(g,m,1.35,.4,.08,1.05);bar(g,m,1.12,.37,-.02,0);bar(g,m,1.35,.4,.08,-1.05)}if(char==='T'){bar(g,m,1.45,.43,0,1.02);bar(g,m,.47,2.45,0,-.05)}g.rotation.x=-Math.PI/2;g.userData.material=m;return g}
function socialLogoTexture(name){
 const canvas=document.createElement('canvas');canvas.width=canvas.height=512;const ctx=canvas.getContext('2d');ctx.clearRect(0,0,512,512);ctx.strokeStyle=ctx.fillStyle='#fff';ctx.lineCap='round';ctx.lineJoin='round';
 if(name==='instagram'){
  ctx.lineWidth=34;ctx.beginPath();ctx.roundRect(98,98,316,316,82);ctx.stroke();ctx.beginPath();ctx.arc(256,256,76,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.arc(359,153,22,0,Math.PI*2);ctx.fill();
 }else if(name==='threads'){
  ctx.lineWidth=32;ctx.beginPath();ctx.moveTo(333,226);ctx.bezierCurveTo(322,143,276,113,221,119);ctx.bezierCurveTo(151,127,125,187,132,266);ctx.bezierCurveTo(139,355,184,397,252,391);ctx.bezierCurveTo(322,385,375,345,374,286);ctx.bezierCurveTo(373,234,334,203,279,205);ctx.bezierCurveTo(222,207,184,237,187,278);ctx.bezierCurveTo(190,314,220,333,255,327);ctx.bezierCurveTo(302,319,330,278,333,226);ctx.stroke();
  ctx.beginPath();ctx.moveTo(212,179);ctx.bezierCurveTo(255,161,320,174,354,213);ctx.stroke();
 }else if(name==='github'){
  const path=new Path2D('M12 2.5a9.7 9.7 0 0 0-3.1 18.9c.5.1.7-.2.7-.5v-1.9c-2.8.6-3.4-1.2-3.4-1.2-.5-1.2-1.1-1.5-1.1-1.5-.9-.6.1-.6.1-.6 1 .1 1.6 1.1 1.6 1.1.9 1.6 2.4 1.1 2.9.9.1-.7.4-1.1.7-1.3-2.2-.3-4.6-1.1-4.6-4.9 0-1.1.4-2 1-2.7-.1-.3-.4-1.3.1-2.7 0 0 .8-.3 2.8 1a9.4 9.4 0 0 1 5 0c1.9-1.3 2.8-1 2.8-1 .5 1.4.2 2.4.1 2.7.6.7 1 1.6 1 2.7 0 3.8-2.3 4.6-4.6 4.9.4.3.7.9.7 1.8v2.7c0 .3.2.6.7.5A9.7 9.7 0 0 0 12 2.5z');ctx.save();ctx.translate(48,48);ctx.scale(17.35,17.35);ctx.fill(path);ctx.restore();
 }else{
  ctx.lineWidth=34;ctx.beginPath();ctx.roundRect(86,130,340,252,38);ctx.stroke();ctx.beginPath();ctx.moveTo(105,158);ctx.lineTo(256,278);ctx.lineTo(407,158);ctx.stroke();
 }
 const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;texture.anisotropy=4;return texture
}
function makeSocialPillow(name,color){
 const group=new THREE.Group(),baseColor=new THREE.Color(color),bodyMaterial=new THREE.MeshPhysicalMaterial({color:baseColor,roughness:.2,clearcoat:1,clearcoatRoughness:.08,sheen:1,sheenColor:baseColor.clone().lerp(new THREE.Color(0xffffff),.42),sheenRoughness:.25});
 const body=new THREE.Mesh(roundedBox(1.22,1.08,.32,.27),bodyMaterial);body.castShadow=true;body.receiveShadow=true;group.add(body);
 const topMaterial=new THREE.MeshPhysicalMaterial({color:baseColor.clone().lerp(new THREE.Color(0xffffff),.12),roughness:.24,clearcoat:.9,clearcoatRoughness:.1});
 const top=new THREE.Mesh(roundedBox(.91,.78,.08,.2),topMaterial);top.position.z=.175;top.castShadow=true;group.add(top);
 const logo=new THREE.Mesh(new THREE.PlaneGeometry(.5,.5),new THREE.MeshBasicMaterial({map:socialLogoTexture(name),transparent:true,alphaTest:.08,depthWrite:false,toneMapped:false,side:THREE.DoubleSide}));logo.position.z=.31;logo.renderOrder=2;group.add(logo);
 group.rotation.x=-Math.PI/2;group.userData.social=name;return group
}
function poolBallTexture(colors){
 const canvas=document.createElement('canvas');canvas.width=768;canvas.height=384;const ctx=canvas.getContext('2d'),panels=12;for(let i=0;i<panels;i++){ctx.fillStyle=i%2?'#fffaf0':colors[(i/2)%colors.length|0];ctx.fillRect(i*canvas.width/panels,0,canvas.width/panels+1,canvas.height)}
 const shine=ctx.createLinearGradient(0,0,canvas.width,canvas.height);shine.addColorStop(0,'rgba(255,255,255,.5)');shine.addColorStop(.4,'rgba(255,255,255,0)');shine.addColorStop(1,'rgba(15,62,99,.18)');ctx.fillStyle=shine;ctx.fillRect(0,0,canvas.width,canvas.height);const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;texture.wrapS=THREE.RepeatWrapping;texture.anisotropy=4;return texture
}
function makePoolBall(colors){const ball=new THREE.Mesh(new THREE.SphereGeometry(.46,28,18),new THREE.MeshPhysicalMaterial({map:poolBallTexture(colors),roughness:.22,clearcoat:1,clearcoatRoughness:.1}));ball.castShadow=true;ball.receiveShadow=true;return ball}
function waveAt(x,z,t){let y=(Math.sin(x*.65+t*.7)+Math.cos(z*.72-t*.56))*config.wave*.45;for(const r of ripples){const d=Math.hypot(x-r.x,z-r.z);y+=Math.sin(d*5-r.age*6)*Math.exp(-d*.34-r.age*.55)*r.strength}return y}
function locate(e){pointer.set(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1);raycaster.setFromCamera(pointer,camera);raycaster.ray.intersectPlane(plane,hit)}
function onPointer(e){if(pointerId!==null&&e.pointerId!==pointerId)return;locate(e);if(socialPress&&socialPress.pointerId===e.pointerId&&Math.hypot(e.clientX-socialPress.x,e.clientY-socialPress.y)>10)socialPress.moved=true;const meshes=[];letters.forEach(l=>l.g.traverse(o=>o.isMesh&&meshes.push(o)));hovered=raycaster.intersectObjects(meshes,false)[0]?.object.userData.body||null;hoveredSocial=raycaster.intersectObjects(socialMeshes,false)[0]?.object.userData.socialBody||null;renderer.domElement.style.cursor=dragged?'grabbing':hoveredSocial?'pointer':hovered?'grab':'crosshair';if(dragged){e.preventDefault();const d=hit.clone().sub(dragged.g.position);d.y=0;dragged.v.addScaledVector(d,config.dragSpring);dragged.g.position.addScaledVector(d,.22);dragged.av.z=-d.x*.08;dragged.av.x=d.z*.07;ripples.push({x:hit.x,z:hit.z,age:0,strength:.04})}}
function down(e){locate(e);const socialHit=raycaster.intersectObjects(socialMeshes,false)[0];if(socialHit){socialPress={body:socialHit.object.userData.socialBody,pointerId:e.pointerId,x:e.clientX,y:e.clientY,moved:false};return}const meshes=[];letters.forEach(l=>l.g.traverse(o=>o.isMesh&&meshes.push(o)));const h=raycaster.intersectObjects(meshes,false)[0];if(h){if(e.cancelable)e.preventDefault();dragged=h.object.userData.body;pointerId=e.pointerId;renderer.domElement.setPointerCapture(e.pointerId)}else ripples.push({x:hit.x,z:hit.z,age:0,strength:.35})}
function openSocial(body){body.velocity.y+=.1;body.angular.z+=.09;ripples.push({x:body.object.position.x,z:body.object.position.z,age:0,strength:.28});if(body.url.startsWith('mailto:'))location.href=body.url;else window.open(body.url,'_blank','noopener,noreferrer')}
function up(e){const socialActivation=e.type==='pointerup'&&socialPress&&socialPress.pointerId===e.pointerId&&!socialPress.moved?socialPress.body:null;socialPress=null;if(dragged){dragged.v.clampLength(0,1);ripples.push({x:dragged.g.position.x,z:dragged.g.position.z,age:0,strength:.24+Math.min(.16,dragged.v.length()*.12)})}dragged=null;pointerId=null;try{renderer.domElement.releasePointerCapture(e.pointerId)}catch{}if(socialActivation)openSocial(socialActivation)}
const clock=new THREE.Clock();let renderFrame=0;
function animate(){
 if(!renderer)return;requestAnimationFrame(animate);if(document.hidden||scrollY>$('#hero').offsetHeight)return;
 renderFrame++;const dt=Math.min(clock.getDelta(),.033),t=clock.elapsedTime,pos=waterGeom.attributes.position;
 ripples.forEach(r=>r.age+=dt);while(ripples[0]?.age>4.5)ripples.shift();
 if(!reduceMotion&&renderFrame%config.frameStride===0){for(let i=0;i<pos.count;i++)pos.setY(i,waveAt(basePositions[i*3],basePositions[i*3+2],t));pos.needsUpdate=true;if(renderFrame%(config.frameStride*4)===0)waterGeom.computeVertexNormals()}
 letters.forEach(l=>{
  const p=l.g.position,w=waveAt(p.x,p.z,t),desiredY=w-.10;
  if(l===dragged){l.v.y*=.72;p.y+=(w+config.dragLift-p.y)*.14}
  else{l.v.y+=(desiredY-p.y)*6.8*dt;l.v.x+=(l.home-p.x)*.045*dt+Math.sin(t*.33+l.phase)*.002;l.v.z+=(l.homeZ-p.z)*.06*dt+Math.cos(t*.4+l.phase)*.0015}
  l.hover+=((hovered===l?1:0)-l.hover)*.16;
  if(l.hover>.02&&l!==dragged){const d=Math.max(.25,hit.distanceTo(p));l.v.y-=l.hover*.012/d;l.av.z+=(hit.x-p.x)*-.0007;if(Math.random()<.035)ripples.push({x:p.x,z:p.z,age:0,strength:.025})}
  l.v.multiplyScalar(Math.pow(config.damping,dt*60));p.addScaledVector(l.v,dt*5.5);
  const targetX=-Math.PI/2+Math.sin(t*.7+l.phase)*.018,targetZ=Math.sin(t*.54+l.phase)*.035;l.av.x+=(targetX-l.g.rotation.x)*.016;l.av.z+=(targetZ-l.g.rotation.z)*.012;l.av.multiplyScalar(Math.pow(config.angularDamping,dt*60));l.g.rotation.x+=l.av.x;l.g.rotation.z+=l.av.z;
  l.compression+=((hovered===l?.91:1)-l.compression)*.16;l.g.scale.set(l.scale/l.compression,l.scale*l.compression,l.scale/l.compression);l.g.userData.material.emissiveIntensity+=(l.hover*.34-l.g.userData.material.emissiveIntensity)*.12;l.g.userData.material.clearcoatRoughness=.07+l.hover*.05;
 });
 // Soft footprint collisions keep the word readable without making it rigid.
 for(let pass=0;pass<2;pass++)for(let i=0;i<letters.length;i++)for(let j=i+1;j<letters.length;j++){const a=letters[i],b=letters[j],ap=a.g.position,bp=b.g.position;if(a===dragged||b===dragged)continue;const dx=bp.x-ap.x,dz=bp.z-ap.z,ox=a.footprint.x+b.footprint.x+.08-Math.abs(dx),oz=a.footprint.z+b.footprint.z+.08-Math.abs(dz);if(ox<=0||oz<=0)continue;const alongX=ox<oz,sign=alongX?(dx>=0?1:-1):(dz>=0?1:-1),correction=Math.min(.035,(alongX?ox:oz)*.12);if(alongX){ap.x-=sign*correction*.5;bp.x+=sign*correction*.5;a.v.x*=.88;b.v.x*=.88}else{ap.z-=sign*correction*.5;bp.z+=sign*correction*.5;a.v.z*=.88;b.v.z*=.88}}
 passiveFloats.forEach(f=>{const p=f.object.position,w=waveAt(p.x,p.z,t),drift=f.drift??1;if(f.social){f.hover+=((hoveredSocial===f?1:0)-f.hover)*.14;const hoverScale=f.baseScale*(1+f.hover*.07);f.object.scale.setScalar(hoverScale)}const targetY=w+f.waterline+(f.social?f.hover*.08:0);f.velocity.y+=(targetY-p.y)*f.buoyancy*dt;f.velocity.x+=(f.homeX-p.x)*.035*dt+Math.sin(t*.3+f.phase)*.0012*drift;f.velocity.z+=(f.homeZ-p.z)*.04*dt+Math.cos(t*.34+f.phase)*.001*drift;f.velocity.multiplyScalar(Math.pow(f.damping??config.damping,dt*60));p.addScaledVector(f.velocity,dt*5);f.angular.x+=(f.baseRotX+Math.sin(t*.55+f.phase)*f.tilt-f.object.rotation.x)*.014;f.angular.z+=(f.baseRotZ+Math.cos(t*.47+f.phase)*f.tilt-f.object.rotation.z)*.014;if(f.yaw)f.angular.y+=(f.baseRotY+Math.sin(t*.24+f.phase)*f.yaw-f.object.rotation.y)*.01;f.angular.multiplyScalar(Math.pow(config.angularDamping,dt*60));f.object.rotation.x+=f.angular.x;f.object.rotation.y+=f.angular.y;f.object.rotation.z+=f.angular.z});
 if(caustics&&renderFrame%config.frameStride===0)caustics.children.forEach((c,i)=>{const pulse=1+Math.sin(t*.48+c.userData.phase)*.13;c.scale.set(pulse,pulse*.72,1);c.material.opacity=.025+Math.sin(t*.62+i)*.012});if(renderer.shadowMap.enabled&&renderFrame%6===0)renderer.shadowMap.needsUpdate=true;
 const hp=+getComputedStyle(document.documentElement).getPropertyValue('--hero-p')||0;camera.position.y=10.7+hp*5.8;camera.position.z=11.7-hp*10;camera.lookAt(0,-.2+hp*.2,-hp*5);renderer.domElement.style.opacity=String(1-clamp((hp-.7)/.22));renderer.render(scene,camera)
}
function init3D(){try{const c=document.createElement('canvas');if(!c.getContext('webgl2'))throw Error('WebGL2 unavailable');scene=new THREE.Scene();scene.background=new THREE.Color(0x77cae4);scene.fog=new THREE.FogExp2(0x77cae4,.022);camera=new THREE.PerspectiveCamera(35,innerWidth/innerHeight,.1,80);camera.position.set(0,10.7,11.7);camera.lookAt(0,-.2,0);renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,innerWidth<700?1:1.25));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=innerWidth>700;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;wrap.append(renderer.domElement);scene.add(new THREE.HemisphereLight(0xeaffff,0x276b8e,2.9));const sun=new THREE.DirectionalLight(0xfff1cc,4.5);sun.position.set(-5,10,5);sun.castShadow=true;scene.add(sun);const floor=new THREE.Mesh(new THREE.PlaneGeometry(30,30),new THREE.MeshStandardMaterial({color:0x4badd2,roughness:.8}));floor.rotation.x=-Math.PI/2;floor.position.y=-1.45;scene.add(floor);waterGeom=new THREE.PlaneGeometry(config.size,config.size,config.segments,config.segments);waterGeom.rotateX(-Math.PI/2);basePositions=Float32Array.from(waterGeom.attributes.position.array);scene.add(new THREE.Mesh(waterGeom,new THREE.MeshPhysicalMaterial({color:0x54bddc,transparent:true,opacity:.72,roughness:.15,clearcoat:1,transmission:.1,depthWrite:false,side:THREE.DoubleSide})));
 const tileCanvas=document.createElement('canvas');tileCanvas.width=tileCanvas.height=256;const tileCtx=tileCanvas.getContext('2d');tileCtx.fillStyle='#62b6d2';tileCtx.fillRect(0,0,256,256);tileCtx.strokeStyle='rgba(232,249,247,.3)';tileCtx.lineWidth=3;for(let n=0;n<=256;n+=64){tileCtx.beginPath();tileCtx.moveTo(n,0);tileCtx.lineTo(n,256);tileCtx.stroke();tileCtx.beginPath();tileCtx.moveTo(0,n);tileCtx.lineTo(256,n);tileCtx.stroke()}for(let i=0;i<80;i++){tileCtx.fillStyle=`rgba(255,255,255,${Math.random()*.035})`;tileCtx.fillRect(Math.random()*256,Math.random()*256,Math.random()*26+4,Math.random()*5+1)}const floorTexture=new THREE.CanvasTexture(tileCanvas);floorTexture.wrapS=floorTexture.wrapT=THREE.RepeatWrapping;floorTexture.repeat.set(7,7);floorTexture.colorSpace=THREE.SRGBColorSpace;const texturedFloor=new THREE.Mesh(new THREE.PlaneGeometry(30,30),new THREE.MeshStandardMaterial({color:0x75c5d8,map:floorTexture,roughness:.82,transparent:true,opacity:.72}));texturedFloor.rotation.x=-Math.PI/2;texturedFloor.position.y=-1.44;scene.add(texturedFloor);
 texturedFloor.material.opacity=.46;floor.receiveShadow=true;texturedFloor.receiveShadow=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.shadowMap.autoUpdate=false;renderer.shadowMap.needsUpdate=true;sun.shadow.mapSize.set(512,512);sun.shadow.camera.left=-9;sun.shadow.camera.right=9;sun.shadow.camera.top=7;sun.shadow.camera.bottom=-7;sun.shadow.bias=-.00035;const waterBounce=new THREE.PointLight(0x76e7ff,9,16,2);waterBounce.position.set(0,1.2,1.5);scene.add(waterBounce);const rim=new THREE.DirectionalLight(0x9fe9ff,1.1);rim.position.set(6,4,-6);scene.add(rim);caustics=new THREE.Group();for(let i=0;i<(innerWidth<700?4:10);i++){const radius=.35+Math.random()*.65,c=new THREE.Mesh(new THREE.RingGeometry(radius,radius+.035+Math.random()*.055,20),new THREE.MeshBasicMaterial({color:0xd9ffff,transparent:true,opacity:.035,depthWrite:false}));c.rotation.x=-Math.PI/2;c.position.set((Math.random()-.5)*18,-1.42,(Math.random()-.5)*13);c.userData.phase=Math.random()*8;caustics.add(c)}scene.add(caustics);
 const chars=[...'ANNETTA'],spacing=[-4.45,-3.02,-1.55,-.05,1.4,2.88,4.25],scale=innerWidth<700?THREE.MathUtils.clamp(innerWidth/1050,.34,.46):.82,wide={A:.72,N:.72,E:.72,T:.72};chars.forEach((ch,i)=>{const g=makeLetter(ch,config.colors[i]),homeZ=innerWidth<700?.9:i%2?.04:-.04;g.position.set(spacing[i]*scale,-.03,homeZ);g.scale.setScalar(scale);scene.add(g);const body={g,home:spacing[i]*scale,homeZ,v:new THREE.Vector3(),av:new THREE.Vector3(),phase:i*1.3,hover:0,compression:1,scale,footprint:{x:wide[ch]*scale,z:1.2*scale}};letters.push(body);g.traverse(o=>{if(o.isMesh)o.userData.body=body})});
 const addModel=gltf=>{const model=gltf.scene;model.scale.setScalar(innerWidth<700?.48:.825);model.position.set(innerWidth<700?0:3.25,.55,innerWidth<700?.5:-2.75);model.rotation.y=-Math.PI*.12;model.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;o.material.envMapIntensity=.75}});scene.add(model);passiveFloats.push({object:model,homeX:model.position.x,homeZ:model.position.z,waterline:.55,buoyancy:5.4,damping:.972,drift:.42,velocity:new THREE.Vector3(),angular:new THREE.Vector3(),baseRotX:model.rotation.x,baseRotY:model.rotation.y,baseRotZ:model.rotation.z,phase:1.4,tilt:.014,yaw:.075})};
 const loadSource=()=>new GLTFLoader().load('./public/assets/3d/annetta.glb',addModel,undefined,error=>console.warn('Annetta model unavailable:',error));const draco=new DRACOLoader();draco.setDecoderPath('https://cdn.jsdelivr.net/npm/three@0.169.0/examples/jsm/libs/draco/');const gltfLoader=new GLTFLoader();gltfLoader.setDRACOLoader(draco);gltfLoader.load('./public/assets/3d/annetta-optimized.glb',addModel,undefined,loadSource);
 const socialSpecs=[['instagram',0xf18cab,-4.7,1.55],['threads',0x252b38,-3.15,3.15],['github',0x58657a,2.9,3.25],['email',0x65c9c4,4.75,2.15]];socialSpecs.forEach(([name,color,x,z],i)=>{const pillow=makeSocialPillow(name,color),mobile=innerWidth<700,scale=mobile?.42:.62;pillow.scale.setScalar(scale);pillow.position.set(mobile?x*.48:x,.15,mobile?z*.4+1:z);scene.add(pillow);const body={object:pillow,social:name,url:socialLinks[name],hover:0,baseScale:scale,homeX:pillow.position.x,homeZ:pillow.position.z,waterline:.14,buoyancy:7.1,drift:1.35,velocity:new THREE.Vector3(),angular:new THREE.Vector3(),baseRotX:pillow.rotation.x,baseRotY:pillow.rotation.y,baseRotZ:pillow.rotation.z,phase:2+i*.9,tilt:.034,yaw:.1};passiveFloats.push(body);pillow.traverse(o=>{if(o.isMesh){o.userData.socialBody=body;socialMeshes.push(o)}})});
 const ballSpecs=[[['#ff6b73','#ffd34e','#4fc4d8'],-3.75,-3.55],[['#7c72e8','#ff8fbd','#4fd39b'],5.45,-1.25],[['#ff8a4d','#56c9e9','#ffe06b'],-5.75,4.1]];ballSpecs.slice(0,innerWidth<700?2:3).forEach(([colors,x,z],i)=>{const ball=makePoolBall(colors),mobile=innerWidth<700,scale=mobile?.62:.9;ball.scale.setScalar(scale);ball.position.set(mobile?x*.45:x,.18,mobile?z*.15+1.25:z);ball.rotation.set(i*.4,.5+i*.7,i*.3);scene.add(ball);passiveFloats.push({object:ball,homeX:ball.position.x,homeZ:ball.position.z,waterline:.18,buoyancy:6.8,damping:.97,drift:1.05,velocity:new THREE.Vector3(),angular:new THREE.Vector3(),baseRotX:ball.rotation.x,baseRotY:ball.rotation.y,baseRotZ:ball.rotation.z,phase:5+i*1.7,tilt:.16,yaw:.28})});
 const ring=new THREE.Mesh(new THREE.TorusGeometry(innerWidth<700?.44:.72,innerWidth<700?.14:.22,16,36),new THREE.MeshPhysicalMaterial({color:0xffe06b,roughness:.28,clearcoat:1,clearcoatRoughness:.13}));ring.rotation.x=Math.PI/2;ring.position.set(innerWidth<700?-2.5:-5.2,.05,innerWidth<700?.6:-2.5);scene.add(ring);passiveFloats.push({object:ring,homeX:ring.position.x,homeZ:ring.position.z,waterline:.08,buoyancy:6.1,damping:.97,drift:.7,velocity:new THREE.Vector3(),angular:new THREE.Vector3(),baseRotX:ring.rotation.x,baseRotY:ring.rotation.y,baseRotZ:ring.rotation.z,phase:.2,tilt:.022,yaw:.045});renderer.domElement.addEventListener('pointermove',onPointer,{passive:false});renderer.domElement.addEventListener('pointerdown',down,{passive:false});renderer.domElement.addEventListener('pointerup',up);renderer.domElement.addEventListener('pointercancel',up);renderer.domElement.addEventListener('pointerleave',()=>{if(pointerId===null){hovered=null;hoveredSocial=null;socialPress=null}});$('.hero-fallback').classList.add('webgl-ready');animate();setTimeout(()=>$('#loader').classList.add('hidden'),550)}catch(err){console.warn('Continuing with lightweight pool hero:',err);$('#loader').classList.add('hidden')}}
addEventListener('resize',()=>{if(!renderer)return;camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});init3D();
