import * as THREE from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { DRACOLoader } from 'three/addons/loaders/DRACOLoader.js';
const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)], clamp=(n,a=0,b=1)=>Math.min(b,Math.max(a,n));
const reduceMotion=matchMedia('(prefers-reduced-motion: reduce)').matches;
const projects=[
 {name:'DPO',full:'Daftar Pencarian Orang',description:'A bounty-poster generator and web toy made for sharing on Threads.',url:'https://dpo.annetta.dev',status:'Live',stack:'Web app · Image tools',role:'Creator & developer',year:'2026',color:'#f06c4f',icon:'DPO'},
 {name:'One Piece',full:'One Piece Bounty Poster Generator',description:'A One Piece-themed tool for creating custom bounty posters.',url:'https://onepiece.annetta.dev',status:'WIP',stack:'Web app · Canvas',role:'Creator & developer',year:'2026',color:'#f5b842',icon:'WANTED'},
 {name:'One Call Away',full:'One Call Away',description:'An app that helps people remember and stay connected with the people who matter to them.',url:'https://onecallaway.annetta.dev',status:'WIP',stack:'Product · Full stack',role:'Product & engineering',year:'2026',color:'#f397aa',icon:'CALL'},
 {name:'Cozy Pomodoro',full:'Cozy Pomodoro',description:'A relaxing Pomodoro app with an animal companion that keeps you company while you focus.',url:'https://cozyapp.annetta.dev',status:'WIP',stack:'Web app · Animation',role:'Creator & developer',year:'2026',color:'#73bda8',icon:'25:00'},
 {name:'Chord Analyzer',full:'Chord Analyzer',description:'Analyzes an MP3 or YouTube video and displays synchronized chord diagrams in real time.',url:'#',status:'Concept',stack:'Audio · AI · Web',role:'Engineering',year:'2026',color:'#838bc9',icon:'Am7'}];
const skills=[['Frontend',8,'ball'],['Backend',8,'board'],['Infrastructure / DevOps',7,'ball'],['Design',7,'board'],['Product Management',7,'ball'],['AI',8,'board']];

projects.forEach((p,i)=>{$('#product-grid').insertAdjacentHTML('beforeend',`<button class="product" type="button" data-index="${i}" role="listitem" aria-label="Open ${p.full}" style="--drink:${p.color}"><span class="bottle-cap"></span><span class="bottle"><b>${p.icon}</b><small>${p.name}</small></span></button>`)});
skills.forEach(([name,score,toy],i)=>{$('#skill-list').insertAdjacentHTML('beforeend',`<div class="skill-row" tabindex="0" style="--score:${score};--delay:${i*.07}s"><div class="skill-name"><span>${String(i+1).padStart(2,'0')}</span><strong>${name}</strong></div><div class="lane"><i></i><b class="lane-toy ${toy}" data-swimmer-slot="${i}" aria-hidden="true"></b></div><output>${score}<small>/10</small></output></div>`)});
let lastProduct;
function closeModal(){const m=$('#project-modal');if(m.open)m.close();document.body.classList.remove('modal-open');lastProduct?.focus()}
function openProject(i){const p=projects[i];lastProduct=$(`.product[data-index="${i}"]`);$('#modal-title').textContent=p.full;$('#modal-description').textContent=p.description;$('#modal-stack').textContent=p.stack;$('#modal-role').textContent=p.role;$('#modal-year').textContent=p.year;$('#modal-status').textContent=p.status;$('#modal-status').className=`status-badge ${p.status==='WIP'?'wip':''}`;$('#project-preview').style.setProperty('--project-color',p.color);$('#project-preview').innerHTML=`<span>${p.icon}</span><strong>${p.full}</strong><small>Project preview</small>`;$('#modal-link').href=p.url;$('#modal-link').style.display=p.url==='#'?'none':'inline-flex';$('#project-modal').showModal();document.body.classList.add('modal-open')}
$('#product-grid').addEventListener('click',e=>{const b=e.target.closest('.product');if(b)openProject(+b.dataset.index)});$('.modal-close').addEventListener('click',closeModal);$('#project-modal').addEventListener('click',e=>{if(e.target===$('#project-modal'))closeModal()});$('#project-modal').addEventListener('close',()=>document.body.classList.remove('modal-open'));
$('#year').textContent=new Date().getFullYear();

const frames=Array.from({length:8},(_,i)=>`./public/assets/characters/bio-walk/${i+1}.png`);
const preloadWalkFrames=()=>Promise.all(frames.map(src=>new Promise(resolve=>{const im=new Image();im.onload=()=>{if(im.decode)im.decode().catch(()=>{}).finally(resolve);else resolve()};im.onerror=resolve;im.src=src}))).then(()=>{$('#walk-sprite').classList.add('ready');$('#return-walk-sprite').classList.add('ready')});if('requestIdleCallback'in window)requestIdleCallback(preloadWalkFrames,{timeout:2200});else setTimeout(preloadWalkFrames,900);
let lastAbout=0,movingTimer;
function updateScroll(){const y=scrollY,vh=innerHeight,hero=$('#hero'),hp=clamp(y/Math.max(1,hero.offsetHeight-vh));document.documentElement.style.setProperty('--hero-p',hp);const about=$('#about'),ar=about.getBoundingClientRect(),ap=clamp((vh-ar.top)/(vh*.65)),walkP=clamp((vh-ar.top)/(vh+ar.height*.78)),walker=$('#walk-sprite');document.documentElement.style.setProperty('--about-p',ap);walker.style.left=`${-12+walkP*124}%`;walker.classList.toggle('active',walkP>0&&walkP<1);if(walkP>0&&walkP<1&&Math.abs(walkP-lastAbout)>.00025){walker.src=frames[Math.floor(walkP*72)%8];walker.classList.add('walking');clearTimeout(movingTimer);movingTimer=setTimeout(()=>{walker.classList.remove('walking');walker.src=frames[0]},130)}lastAbout=walkP;const sr=$('#skills').getBoundingClientRect(),sp=clamp((vh-sr.top)/(vh+sr.height*.25));document.documentElement.style.setProperty('--skills-p',sp);const rr=$('.return-walk').getBoundingClientRect(),rp=clamp((vh*.88-rr.top)/(vh+rr.height*.35));document.documentElement.style.setProperty('--return-p',rp);if(rp>0&&rp<1)$('#return-walk-sprite').src=frames[Math.floor(rp*48)%8];$('#site-nav').classList.toggle('visible',hp>.82||y>hero.offsetHeight-vh*.1);let active='';['about','projects','skills','contact'].forEach(id=>{if($(`#${id}`).getBoundingClientRect().top<vh*.5)active=id});$$('.site-nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#${active}`))}
let scrollUpdateQueued=false;function scheduleScrollUpdate(){if(scrollUpdateQueued)return;scrollUpdateQueued=true;requestAnimationFrame(()=>{scrollUpdateQueued=false;updateScroll()})}addEventListener('scroll',scheduleScrollUpdate,{passive:true});addEventListener('resize',scheduleScrollUpdate);updateScroll();
new IntersectionObserver(entries=>entries.forEach(entry=>entry.target.classList.toggle('scene-entered',entry.isIntersecting)),{threshold:.18}).observe($('#projects'));
$$('.paper-world,.tile-world').forEach(section=>section.addEventListener('pointerdown',event=>{if(event.target.closest('a,button,[tabindex]'))return;const ripple=document.createElement('i');ripple.className='surface-ripple';const rect=section.getBoundingClientRect();ripple.style.left=`${event.clientX-rect.left}px`;ripple.style.top=`${event.clientY-rect.top}px`;section.append(ripple);ripple.addEventListener('animationend',()=>ripple.remove())},{passive:true}));
$$('[data-skip-intro]').forEach(b=>b.addEventListener('click',e=>{sessionStorage.setItem('annetta-intro-skipped','1');$('#loader').classList.add('hidden');$('#site-nav').classList.add('visible');$('#about').scrollIntoView({behavior:reduceMotion?'auto':'smooth'});if(e.detail===0)setTimeout(()=>$('#about').focus(),350)}));

const wrap=$('#canvas-wrap'),letters=[],passiveFloats=[],ripples=[],raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2(9,9),hit=new THREE.Vector3(),plane=new THREE.Plane(new THREE.Vector3(0,1,0),0);
let renderer,scene,camera,waterGeom,basePositions,caustics,dragged=null,hovered=null,pointerId=null;
const config={size:30,segments:innerWidth<700?20:36,wave:.10,damping:.965,angularDamping:.94,dragSpring:.15,dragLift:.82,colors:[0xff6e7e,0xffbd55,0x78d5bb,0x70b9ef,0xb59ae8,0xff8eb5,0x50c3d2]};
function roundedBox(w,h,d,r=.2){const s=new THREE.Shape(),x=-w/2,y=-h/2;s.moveTo(x+r,y);s.lineTo(x+w-r,y);s.quadraticCurveTo(x+w,y,x+w,y+r);s.lineTo(x+w,y+h-r);s.quadraticCurveTo(x+w,y+h,x+w-r,y+h);s.lineTo(x+r,y+h);s.quadraticCurveTo(x,y+h,x,y+h-r);s.lineTo(x,y+r);s.quadraticCurveTo(x,y,x+r,y);const g=new THREE.ExtrudeGeometry(s,{depth:d,bevelEnabled:true,bevelSegments:3,bevelSize:r*.4,bevelThickness:r*.4,curveSegments:6});g.center();return g}
function bar(g,m,w,h,x,y,a=0){const o=new THREE.Mesh(roundedBox(w,h,.58,Math.min(w,h)*.3),m);o.position.set(x,y,0);o.rotation.z=a;o.castShadow=true;g.add(o)}
function makeLetter(char,color){const g=new THREE.Group(),m=new THREE.MeshPhysicalMaterial({color,emissive:new THREE.Color(color).multiplyScalar(.12),emissiveIntensity:0,roughness:.2,clearcoat:1,clearcoatRoughness:.07,sheen:1,sheenColor:new THREE.Color(color).lerp(new THREE.Color(0xffffff),.5),sheenRoughness:.22});if(char==='A'){bar(g,m,.47,2.45,-.38,0,-.23);bar(g,m,.47,2.45,.38,0,.23);bar(g,m,.92,.36,0,-.04)}if(char==='N'){bar(g,m,.46,2.5,-.48,0);bar(g,m,.46,2.5,.48,0);bar(g,m,.48,2.63,0,0,.37)}if(char==='E'){bar(g,m,.46,2.5,-.43,0);bar(g,m,1.35,.4,.08,1.05);bar(g,m,1.12,.37,-.02,0);bar(g,m,1.35,.4,.08,-1.05)}if(char==='T'){bar(g,m,1.45,.43,0,1.02);bar(g,m,.47,2.45,0,-.05)}g.rotation.x=-Math.PI/2;g.userData.material=m;return g}
function makeSocialPillow(label,color){const canvas=document.createElement('canvas');canvas.width=canvas.height=256;const ctx=canvas.getContext('2d');ctx.fillStyle=`#${new THREE.Color(color).getHexString()}`;ctx.fillRect(0,0,256,256);const shine=ctx.createLinearGradient(0,0,256,256);shine.addColorStop(0,'rgba(255,255,255,.68)');shine.addColorStop(.38,'rgba(255,255,255,.08)');shine.addColorStop(1,'rgba(0,45,80,.12)');ctx.fillStyle=shine;ctx.fillRect(0,0,256,256);ctx.fillStyle='#fff';ctx.font='700 84px DM Sans, sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(label,128,132);const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;const pillow=new THREE.Mesh(roundedBox(1.05,1.05,.34,.27),new THREE.MeshPhysicalMaterial({map:texture,color:0xffffff,roughness:.18,clearcoat:1,clearcoatRoughness:.08}));pillow.rotation.x=-Math.PI/2;pillow.castShadow=true;return pillow}
function waveAt(x,z,t){let y=(Math.sin(x*.65+t*.7)+Math.cos(z*.72-t*.56))*config.wave*.45;for(const r of ripples){const d=Math.hypot(x-r.x,z-r.z);y+=Math.sin(d*5-r.age*6)*Math.exp(-d*.34-r.age*.55)*r.strength}return y}
function locate(e){pointer.set(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1);raycaster.setFromCamera(pointer,camera);raycaster.ray.intersectPlane(plane,hit)}
function onPointer(e){if(pointerId!==null&&e.pointerId!==pointerId)return;locate(e);const meshes=[];letters.forEach(l=>l.g.traverse(o=>o.isMesh&&meshes.push(o)));hovered=raycaster.intersectObjects(meshes,false)[0]?.object.userData.body||null;renderer.domElement.style.cursor=dragged?'grabbing':hovered?'grab':'crosshair';if(dragged){e.preventDefault();const d=hit.clone().sub(dragged.g.position);d.y=0;dragged.v.addScaledVector(d,config.dragSpring);dragged.g.position.addScaledVector(d,.22);dragged.av.z=-d.x*.08;dragged.av.x=d.z*.07;ripples.push({x:hit.x,z:hit.z,age:0,strength:.04})}}
function down(e){locate(e);const meshes=[];letters.forEach(l=>l.g.traverse(o=>o.isMesh&&meshes.push(o)));const h=raycaster.intersectObjects(meshes,false)[0];if(h){if(e.cancelable)e.preventDefault();dragged=h.object.userData.body;pointerId=e.pointerId;renderer.domElement.setPointerCapture(e.pointerId)}else ripples.push({x:hit.x,z:hit.z,age:0,strength:.35})}
function up(e){if(dragged){dragged.v.clampLength(0,1);ripples.push({x:dragged.g.position.x,z:dragged.g.position.z,age:0,strength:.24+Math.min(.16,dragged.v.length()*.12)})}dragged=null;pointerId=null;try{renderer.domElement.releasePointerCapture(e.pointerId)}catch{}}
const clock=new THREE.Clock();let renderFrame=0;
function animate(){
 if(!renderer)return;requestAnimationFrame(animate);if(document.hidden||scrollY>$('#hero').offsetHeight)return;
 renderFrame++;const dt=Math.min(clock.getDelta(),.033),t=clock.elapsedTime,pos=waterGeom.attributes.position;
 ripples.forEach(r=>r.age+=dt);while(ripples[0]?.age>4.5)ripples.shift();
 if(!reduceMotion&&renderFrame%2===0){for(let i=0;i<pos.count;i++)pos.setY(i,waveAt(basePositions[i*3],basePositions[i*3+2],t));pos.needsUpdate=true;if(renderFrame%8===0)waterGeom.computeVertexNormals()}
 letters.forEach(l=>{
  const p=l.g.position,w=waveAt(p.x,p.z,t),desiredY=w-.10;
  if(l===dragged){l.v.y*=.72;p.y+=(w+config.dragLift-p.y)*.14}
  else{l.v.y+=(desiredY-p.y)*6.8*dt;l.v.x+=(l.home-p.x)*.045*dt+Math.sin(t*.33+l.phase)*.002;l.v.z+=-p.z*.06*dt+Math.cos(t*.4+l.phase)*.0015}
  l.hover+=((hovered===l?1:0)-l.hover)*.16;
  if(l.hover>.02&&l!==dragged){const d=Math.max(.25,hit.distanceTo(p));l.v.y-=l.hover*.012/d;l.av.z+=(hit.x-p.x)*-.0007;if(Math.random()<.035)ripples.push({x:p.x,z:p.z,age:0,strength:.025})}
  l.v.multiplyScalar(Math.pow(config.damping,dt*60));p.addScaledVector(l.v,dt*5.5);
  const targetX=-Math.PI/2+Math.sin(t*.7+l.phase)*.018,targetZ=Math.sin(t*.54+l.phase)*.035;l.av.x+=(targetX-l.g.rotation.x)*.016;l.av.z+=(targetZ-l.g.rotation.z)*.012;l.av.multiplyScalar(Math.pow(config.angularDamping,dt*60));l.g.rotation.x+=l.av.x;l.g.rotation.z+=l.av.z;
  l.compression+=((hovered===l?.91:1)-l.compression)*.16;l.g.scale.set(l.scale/l.compression,l.scale*l.compression,l.scale/l.compression);l.g.userData.material.emissiveIntensity+=(l.hover*.34-l.g.userData.material.emissiveIntensity)*.12;l.g.userData.material.clearcoatRoughness=.07+l.hover*.05;
 });
 // Soft footprint collisions keep the word readable without making it rigid.
 for(let pass=0;pass<2;pass++)for(let i=0;i<letters.length;i++)for(let j=i+1;j<letters.length;j++){const a=letters[i],b=letters[j],ap=a.g.position,bp=b.g.position;if(a===dragged||b===dragged)continue;const dx=bp.x-ap.x,dz=bp.z-ap.z,ox=a.footprint.x+b.footprint.x+.08-Math.abs(dx),oz=a.footprint.z+b.footprint.z+.08-Math.abs(dz);if(ox<=0||oz<=0)continue;const alongX=ox<oz,sign=alongX?(dx>=0?1:-1):(dz>=0?1:-1),correction=Math.min(.035,(alongX?ox:oz)*.12);if(alongX){ap.x-=sign*correction*.5;bp.x+=sign*correction*.5;a.v.x*=.88;b.v.x*=.88}else{ap.z-=sign*correction*.5;bp.z+=sign*correction*.5;a.v.z*=.88;b.v.z*=.88}}
 passiveFloats.forEach(f=>{const p=f.object.position,w=waveAt(p.x,p.z,t),targetY=w+f.waterline,drift=f.drift??1;f.velocity.y+=(targetY-p.y)*f.buoyancy*dt;f.velocity.x+=(f.homeX-p.x)*.035*dt+Math.sin(t*.3+f.phase)*.0012*drift;f.velocity.z+=(f.homeZ-p.z)*.04*dt+Math.cos(t*.34+f.phase)*.001*drift;f.velocity.multiplyScalar(Math.pow(f.damping??config.damping,dt*60));p.addScaledVector(f.velocity,dt*5);f.angular.x+=(f.baseRotX+Math.sin(t*.55+f.phase)*f.tilt-f.object.rotation.x)*.014;f.angular.z+=(f.baseRotZ+Math.cos(t*.47+f.phase)*f.tilt-f.object.rotation.z)*.014;if(f.yaw)f.angular.y+=(f.baseRotY+Math.sin(t*.24+f.phase)*f.yaw-f.object.rotation.y)*.01;f.angular.multiplyScalar(Math.pow(config.angularDamping,dt*60));f.object.rotation.x+=f.angular.x;f.object.rotation.y+=f.angular.y;f.object.rotation.z+=f.angular.z});
 if(caustics&&renderFrame%2===0)caustics.children.forEach((c,i)=>{const pulse=1+Math.sin(t*.48+c.userData.phase)*.13;c.scale.set(pulse,pulse*.72,1);c.material.opacity=.025+Math.sin(t*.62+i)*.012});if(renderer.shadowMap.enabled&&renderFrame%6===0)renderer.shadowMap.needsUpdate=true;
 const hp=+getComputedStyle(document.documentElement).getPropertyValue('--hero-p')||0;camera.position.y=10.7+hp*5.8;camera.position.z=11.7-hp*10;camera.lookAt(0,-.2+hp*.2,-hp*5);renderer.domElement.style.opacity=String(1-clamp((hp-.7)/.22));renderer.render(scene,camera)
}
function init3D(){try{const c=document.createElement('canvas');if(!c.getContext('webgl2'))throw Error('WebGL2 unavailable');scene=new THREE.Scene();scene.background=new THREE.Color(0x77cae4);scene.fog=new THREE.FogExp2(0x77cae4,.022);camera=new THREE.PerspectiveCamera(35,innerWidth/innerHeight,.1,80);camera.position.set(0,10.7,11.7);camera.lookAt(0,-.2,0);renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,innerWidth<700?1.25:1.5));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=innerWidth>700;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;wrap.append(renderer.domElement);scene.add(new THREE.HemisphereLight(0xeaffff,0x276b8e,2.9));const sun=new THREE.DirectionalLight(0xfff1cc,4.5);sun.position.set(-5,10,5);sun.castShadow=true;scene.add(sun);const floor=new THREE.Mesh(new THREE.PlaneGeometry(30,30),new THREE.MeshStandardMaterial({color:0x4badd2,roughness:.8}));floor.rotation.x=-Math.PI/2;floor.position.y=-1.45;scene.add(floor);waterGeom=new THREE.PlaneGeometry(config.size,config.size,config.segments,config.segments);waterGeom.rotateX(-Math.PI/2);basePositions=Float32Array.from(waterGeom.attributes.position.array);scene.add(new THREE.Mesh(waterGeom,new THREE.MeshPhysicalMaterial({color:0x54bddc,transparent:true,opacity:.72,roughness:.15,clearcoat:1,transmission:.1,depthWrite:false,side:THREE.DoubleSide})));
 const tileCanvas=document.createElement('canvas');tileCanvas.width=tileCanvas.height=256;const tileCtx=tileCanvas.getContext('2d');tileCtx.fillStyle='#62b6d2';tileCtx.fillRect(0,0,256,256);tileCtx.strokeStyle='rgba(232,249,247,.3)';tileCtx.lineWidth=3;for(let n=0;n<=256;n+=64){tileCtx.beginPath();tileCtx.moveTo(n,0);tileCtx.lineTo(n,256);tileCtx.stroke();tileCtx.beginPath();tileCtx.moveTo(0,n);tileCtx.lineTo(256,n);tileCtx.stroke()}for(let i=0;i<80;i++){tileCtx.fillStyle=`rgba(255,255,255,${Math.random()*.035})`;tileCtx.fillRect(Math.random()*256,Math.random()*256,Math.random()*26+4,Math.random()*5+1)}const floorTexture=new THREE.CanvasTexture(tileCanvas);floorTexture.wrapS=floorTexture.wrapT=THREE.RepeatWrapping;floorTexture.repeat.set(7,7);floorTexture.colorSpace=THREE.SRGBColorSpace;const texturedFloor=new THREE.Mesh(new THREE.PlaneGeometry(30,30),new THREE.MeshStandardMaterial({color:0x75c5d8,map:floorTexture,roughness:.82,transparent:true,opacity:.72}));texturedFloor.rotation.x=-Math.PI/2;texturedFloor.position.y=-1.44;scene.add(texturedFloor);
 renderer.setPixelRatio(Math.min(devicePixelRatio,innerWidth<700?1:1.25));texturedFloor.material.opacity=.46;floor.receiveShadow=true;texturedFloor.receiveShadow=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.shadowMap.autoUpdate=false;renderer.shadowMap.needsUpdate=true;sun.shadow.mapSize.set(512,512);sun.shadow.camera.left=-9;sun.shadow.camera.right=9;sun.shadow.camera.top=7;sun.shadow.camera.bottom=-7;sun.shadow.bias=-.00035;const waterBounce=new THREE.PointLight(0x76e7ff,9,16,2);waterBounce.position.set(0,1.2,1.5);scene.add(waterBounce);const rim=new THREE.DirectionalLight(0x9fe9ff,1.1);rim.position.set(6,4,-6);scene.add(rim);caustics=new THREE.Group();for(let i=0;i<(innerWidth<700?4:10);i++){const radius=.35+Math.random()*.65,c=new THREE.Mesh(new THREE.RingGeometry(radius,radius+.035+Math.random()*.055,20),new THREE.MeshBasicMaterial({color:0xd9ffff,transparent:true,opacity:.035,depthWrite:false}));c.rotation.x=-Math.PI/2;c.position.set((Math.random()-.5)*18,-1.42,(Math.random()-.5)*13);c.userData.phase=Math.random()*8;caustics.add(c)}scene.add(caustics);
 const chars=[...'ANNETTA'],spacing=[-4.45,-3.02,-1.55,-.05,1.4,2.88,4.25],scale=innerWidth<700?THREE.MathUtils.clamp(innerWidth/1050,.34,.46):.82,wide={A:.72,N:.72,E:.72,T:.72};chars.forEach((ch,i)=>{const g=makeLetter(ch,config.colors[i]);g.position.set(spacing[i]*scale,-.03,i%2?.04:-.04);g.scale.setScalar(scale);scene.add(g);const body={g,home:spacing[i]*scale,v:new THREE.Vector3(),av:new THREE.Vector3(),phase:i*1.3,hover:0,compression:1,scale,footprint:{x:wide[ch]*scale,z:1.2*scale}};letters.push(body);g.traverse(o=>{if(o.isMesh)o.userData.body=body})});
 const addModel=gltf=>{const model=gltf.scene;model.scale.setScalar(innerWidth<700?.48:.825);model.position.set(innerWidth<700?0:3.25,.55,innerWidth<700?-2.35:-2.75);model.rotation.y=-Math.PI*.12;model.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;o.material.envMapIntensity=.75}});scene.add(model);passiveFloats.push({object:model,homeX:model.position.x,homeZ:model.position.z,waterline:.55,buoyancy:5.4,damping:.972,drift:.42,velocity:new THREE.Vector3(),angular:new THREE.Vector3(),baseRotX:model.rotation.x,baseRotY:model.rotation.y,baseRotZ:model.rotation.z,phase:1.4,tilt:.014,yaw:.075})};
 const loadSource=()=>new GLTFLoader().load('./public/assets/3d/annetta.glb',addModel,undefined,error=>console.warn('Annetta model unavailable:',error));const draco=new DRACOLoader();draco.setDecoderPath('https://cdn.jsdelivr.net/npm/three@0.169.0/examples/jsm/libs/draco/');const gltfLoader=new GLTFLoader();gltfLoader.setDRACOLoader(draco);gltfLoader.load('./public/assets/3d/annetta-optimized.glb',addModel,undefined,loadSource);
 const socialSpecs=[['◎',0xf18cab,-4.7,1.55],['Th',0x252b38,-3.15,3.15],['GH',0x58657a,2.9,3.25],['@',0x65c9c4,4.75,2.15],['in',0x4285c5,3.75,1.05]];socialSpecs.forEach(([label,color,x,z],i)=>{const pillow=makeSocialPillow(label,color),mobile=innerWidth<700,scale=mobile?.42:.62;pillow.scale.setScalar(scale);pillow.position.set(mobile?x*.48:x,.15,mobile?z+1:z);scene.add(pillow);passiveFloats.push({object:pillow,homeX:pillow.position.x,homeZ:pillow.position.z,waterline:.14,buoyancy:7.1,drift:1.35,velocity:new THREE.Vector3(),angular:new THREE.Vector3(),baseRotX:pillow.rotation.x,baseRotY:pillow.rotation.y,baseRotZ:pillow.rotation.z,phase:2+i*.9,tilt:.034,yaw:.1})});
 const ring=new THREE.Mesh(new THREE.TorusGeometry(innerWidth<700?.44:.72,innerWidth<700?.14:.22,16,36),new THREE.MeshPhysicalMaterial({color:0xffe06b,roughness:.28,clearcoat:1,clearcoatRoughness:.13}));ring.rotation.x=Math.PI/2;ring.position.set(innerWidth<700?-2.5:-5.2,.05,-2.5);scene.add(ring);passiveFloats.push({object:ring,homeX:ring.position.x,homeZ:ring.position.z,waterline:.08,buoyancy:6.1,damping:.97,drift:.7,velocity:new THREE.Vector3(),angular:new THREE.Vector3(),baseRotX:ring.rotation.x,baseRotY:ring.rotation.y,baseRotZ:ring.rotation.z,phase:.2,tilt:.022,yaw:.045});renderer.domElement.addEventListener('pointermove',onPointer,{passive:false});renderer.domElement.addEventListener('pointerdown',down,{passive:false});renderer.domElement.addEventListener('pointerup',up);renderer.domElement.addEventListener('pointercancel',up);$('.hero-fallback').classList.add('webgl-ready');animate();setTimeout(()=>$('#loader').classList.add('hidden'),550)}catch(err){console.warn('Continuing with lightweight pool hero:',err);$('#loader').classList.add('hidden')}}
addEventListener('resize',()=>{if(!renderer)return;camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});if(sessionStorage.getItem('annetta-intro-skipped')==='1'){$('#loader').classList.add('hidden');$('#site-nav').classList.add('visible')}init3D();
